/*datos de los socos*/
INSERT INTO `socios` (`fecha_nacimiento`, `numero_casa`, `personas_dependientes`, `tiempo_residencia`, `id`, `apellido`, `nombres`, `carpeta`, `cedula`, `celular`, `ciudad`, `correo`, `direccion`, `estado_civil`, `genero`, `lugar_nacimiento`, `parroquia`, `profesion`, `propietario`, `provincia`, `referencia`, `sector`, `telefono`, `telefono_propietario`, `tipo_casa`) VALUES ('1955-06-13', '1', '5', '30', NULL, 'Nieves', 'Roberto', 'Solicitud de un credito', '0105577985', '0985586935', 'Cuenca', 'rn@gmail.com', 'Chilcapamba-Via al Valle', 'Casado', 'Masculino', 'Cuenca-Ecuador', 'Gualalcay', 'Developer', 'Juan', 'Azuay', 'Bryan', 'San Jose', '0985586935', '0123654789', 'Ladrillo');
INSERT INTO `socios` (`fecha_nacimiento`, `numero_casa`, `personas_dependientes`, `tiempo_residencia`, `id`, `apellido`, `nombres`, `carpeta`, `cedula`, `celular`, `ciudad`, `correo`, `direccion`, `estado_civil`, `genero`, `lugar_nacimiento`, `parroquia`, `profesion`, `propietario`, `provincia`, `referencia`, `sector`, `telefono`, `telefono_propietario`, `tipo_casa`) VALUES ('1955-06-13', '1', '3', '15', NULL, 'Farez', 'Bryan', 'Solicitud de un credito', '0105577986', '0985586935', 'Cuenca', 'br@gmail.com', 'Chilcapamba-Via al Valle', 'Casado', 'Masculino', 'Cuenca-Ecuador', 'Victoria', 'Docente', 'Pedro', 'Azuay', 'Stiven', 'El cisne', '0985586935', '0123654789', 'Ladrillo');
INSERT INTO `socios` (`fecha_nacimiento`, `numero_casa`, `personas_dependientes`, `tiempo_residencia`, `id`, `apellido`, `nombres`, `carpeta`, `cedula`, `celular`, `ciudad`, `correo`, `direccion`, `estado_civil`, `genero`, `lugar_nacimiento`, `parroquia`, `profesion`, `propietario`, `provincia`, `referencia`, `sector`, `telefono`, `telefono_propietario`, `tipo_casa`) VALUES ('1955-06-13', '1', '3', '10', NULL, 'Matute', 'John', 'Solicitud de un credito', '0105577987', '0985586935', 'Cuenca', 'jm@gmail.com', 'Chilcapamba-Via al Valle', 'Casado', 'Masculino', 'Cuenca-Ecuador', 'Gualalcay', 'Developer', 'Rosa', 'Azuay', 'Kathy', 'Chilcapamba', '0985586935', '0123654789', 'Ladrillo');
INSERT INTO `socios` (`fecha_nacimiento`, `numero_casa`, `personas_dependientes`, `tiempo_residencia`, `id`, `apellido`, `nombres`, `carpeta`, `cedula`, `celular`, `ciudad`, `correo`, `direccion`, `estado_civil`, `genero`, `lugar_nacimiento`, `parroquia`, `profesion`, `propietario`, `provincia`, `referencia`, `sector`, `telefono`, `telefono_propietario`, `tipo_casa`) VALUES ('1955-06-13', '1', '6', '30', NULL, 'Nieves', 'Luis', 'Solicitud de un credito', '0105577988', '0985586935', 'Cuenca', 'ln@gmail.com', 'Chilcapamba-Via al Valle', 'Casado', 'Masculino', 'Cuenca-Ecuador', 'Cuatro esquinas', 'Docente', 'Juan', 'Azuay', 'Daniela', 'Chilcapamba', '0985586935', '0123654789', 'Bloque');

/*datos CONYUGE*/
INSERT INTO `conyugue` (`fecha_nacimiento`, `id`, `socio_id`, `apellido`, `nombre`, `area`, `cedula`, `direccion`, `ocupacion`, `profesion`, `telefono`) VALUES ('1975-06-24', NULL, '1', 'Fernandez', 'Gladys', 'Ama de casa', '0123456789', 'Victoria Alta', 'Ama de casa', 'Ama de casa', '0985583598');
INSERT INTO `conyugue` (`fecha_nacimiento`, `id`, `socio_id`, `apellido`, `nombre`, `area`, `cedula`, `direccion`, `ocupacion`, `profesion`, `telefono`) VALUES ('1985-06-24', NULL, '2', 'Loma', 'Carmen', 'salud', '0123456781', 'Victoria Alta', 'Auxiliar', 'Enfermera', '0985583591');
INSERT INTO `conyugue` (`fecha_nacimiento`, `id`, `socio_id`, `apellido`, `nombre`, `area`, `cedula`, `direccion`, `ocupacion`, `profesion`, `telefono`) VALUES ('1975-06-24', NULL, '3', 'Farez', 'Eulalia', 'Docente', '0123456782', 'Chilcapamba', 'Educacion Basica', 'Profesora', '0985583592');

/*datos inmobiliarios false=b'00000'   true=b'1'*/
INSERT INTO `inmobiliarios` (`hipotecado`, `valor`, `id`, `socio_id`, `direccion`, `institucion`, `tipo_propiedad`) VALUES (b'00000', '4000', NULL, '1', 'Chilcapamba-Via al Valle', 'Ninguna', 'Casa');
INSERT INTO `inmobiliarios` (`hipotecado`, `valor`, `id`, `socio_id`, `direccion`, `institucion`, `tipo_propiedad`) VALUES (b'1', '5200', NULL, '2', 'San Jose', 'E&A Broks', 'Casa');
INSERT INTO `inmobiliarios` (`hipotecado`, `valor`, `id`, `socio_id`, `direccion`, `institucion`, `tipo_propiedad`) VALUES (b'00000', '2000', NULL, '4', 'Chilcapamba-Via al Valle', 'Ninguna', 'Casa');

/*datos Referencias Personales*/
INSERT INTO `referencias_personales` (`confirmacion`, `id`, `socio_id`, `apellido`, `direccion`, `nombre`, `parentesco`, `telefono`) VALUES (b'1', NULL, '1', 'Perez', 'Don Bosco', 'Jeff', 'Jefe del Trabajo', '0120236548');
INSERT INTO `referencias_personales` (`confirmacion`, `id`, `socio_id`, `apellido`, `direccion`, `nombre`, `parentesco`, `telefono`) VALUES (b'1', NULL, '2', 'Villa', 'Kennedy', 'Isacc', 'Tio', '0120236545');
INSERT INTO `referencias_personales` (`confirmacion`, `id`, `socio_id`, `apellido`, `direccion`, `nombre`, `parentesco`, `telefono`) VALUES (b'1', NULL, '3', 'Benavides', 'Ricaurte', 'Jose', 'Vecino', '0120236547');

/*datos Trabajo*/
INSERT INTO `trabajo` (`anios_trabajados`, `id`, `socio_id`, `area`, `direccion`, `nombre`, `ocupacio`, `telefono`) VALUES ('25', NULL, '1', 'Software', 'Octavio Chacon 11-2 y tranversal', 'Tec Azuay', 'Developer', '1236541205');
INSERT INTO `trabajo` (`anios_trabajados`, `id`, `socio_id`, `area`, `direccion`, `nombre`, `ocupacio`, `telefono`) VALUES ('5', NULL, '2', 'Software', 'Av. Espania', 'UPS', 'Developer', '1236541208');
INSERT INTO `trabajo` (`anios_trabajados`, `id`, `socio_id`, `area`, `direccion`, `nombre`, `ocupacio`, `telefono`) VALUES ('25', NULL, '3', 'Software', 'Parque Industrial', 'Llantera', 'Obrero', '1236541405');
INSERT INTO `trabajo` (`anios_trabajados`, `id`, `socio_id`, `area`, `direccion`, `nombre`, `ocupacio`, `telefono`) VALUES ('12', NULL, '4', 'Software', 'Octavio Chacon 11-2 y tranversal', 'Tec Azuay', 'Developer', '1236588205');

/*datos vehiculo*/
INSERT INTO `vehiculos` (`anio_fabricacion`, `valor`, `id`, `socio_id`, `marca`, `numero_placa`, `tipo_vehiculo`) VALUES ('2000-06-20', '5200', NULL, '1', 'Nissan', 'AP-000050', 'Automovil');
INSERT INTO `vehiculos` (`anio_fabricacion`, `valor`, `id`, `socio_id`, `marca`, `numero_placa`, `tipo_vehiculo`) VALUES ('1990-06-20', '8200', NULL, '2', 'Toyota', 'AP-000074', 'Automovil');
INSERT INTO `vehiculos` (`anio_fabricacion`, `valor`, `id`, `socio_id`, `marca`, `numero_placa`, `tipo_vehiculo`) VALUES ('2010-06-20', '9200', NULL, '3', 'Hyundai', 'TAP-000054', 'Automovil');
INSERT INTO `vehiculos` (`anio_fabricacion`, `valor`, `id`, `socio_id`, `marca`, `numero_placa`, `tipo_vehiculo`) VALUES ('2009-06-20', '7200', NULL, '4', 'Nissan', 'AP-000216', 'Automovil');
